/* 🤖 this file was generated by svg-to-ts */
export default function ArrowRight({ fill = "#8B898E" }: { fill?: string }) {
  return (
    <svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <mask
        id="mask0_468_23445"
        style={{ maskType: "alpha" }}
        maskUnits="userSpaceOnUse"
        x="5"
        y="5"
        width="14"
        height="14"
      >
        <path
          d="M12 5L5 12L12 19L13.2281 17.7719L8.35672 12.8596H19V11.1404H8.35672L13.2281 6.22807L12 5Z"
          fill="white"
        />
      </mask>
      <g mask="url(#mask0_468_23445)">
        <rect width="24" height="24" fill={fill} />
      </g>
    </svg>
  );
}
