/* 🤖 this file was generated by svg-to-ts */
export default function MobileMenu({ fill = "#8B898E" }: { fill?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
      <mask
        id="a"
        width="16"
        height="10"
        x="4"
        y="7"
        maskUnits="userSpaceOnUse"
        style={{ maskType: "alpha" }}
      >
        <path
          fill="#fff"
          d="M4.5 7h15v1.68h-15zm0 5.82v-1.64h15v1.64zm0 4.18v-1.68h15V17z"
        />
      </mask>
      <g mask="url(#a)">
        <path fill={fill} d="M0 0h24v24H0z" />
      </g>
    </svg>
  );
}
